version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn build:prod
  deploy-beta:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn build:prod
      - run:
          name: Deploy to beta.ravens-scans.com
          command: |
            sudo apt-get update
            echo "Initiating Push site beta-api.ravens-scans.com"
            find . -name '*' -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ravens-scans.com/beta-api.ravens-scans.com/{} \;
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-beta:
          requires:
            - build
          filters:
            branches:
              only: beta-ravens
